@hostname = 127.0.0.1:5000
@endpoint = /v1
@baseUrl = http://{{hostname}}{{endpoint}}
@contentType = application/json


### Exams

GET {{baseUrl}}/exams

###

POST {{baseUrl}}/Exams
Content-Type: application/json

{
  "name": "Ex1",
  "maxScore": 20,
  "gradingScale": {
    "aPercent": 80,
    "bPercent": 70,
    "cPercent": 60,
    "dPercent": 50,
    "ePercent": 40,
    "fPercent": 30
  }
}

###

OPTIONS {{baseUrl}}/Exams

###

PUT {{baseUrl}}/Exams/2
Content-Type: application/json

{
  "id": 2,
  "name": "Update",
  "maxScore": 20,
  "gradingScale": {
    "aPercent": 80,
    "bPercent": 70,
    "cPercent": 60,
    "dPercent": 50,
    "ePercent": 40,
    "fPercent": 30
  }
}

### Students

GET {{baseUrl}}/students

### 

POST {{baseUrl}}/students
Content-Type: application/json

{
  "firstName": "Foo",
  "lastName": "Bar"
}

###

PUT {{baseUrl}}/Students/7
Content-Type: application/json

{
  "id": 7,
  "firstName": "Neu",
  "lastName": "Test"
}

###

DELETE {{baseUrl}}/Students/8

### Scores

GET {{baseUrl}}/Scores

###

POST {{baseUrl}}/Scores
Content-Type: application/json

{
  "studentId": 10,
  "examId": 1,
  "value": 10
}

###

DELETE {{baseUrl}}/Scores/3

###

PUT {{baseUrl}}/Scores/5
Content-Type: application/json

{
  "id": 5,
  "studentId": 6,
  "examId": 1,
  "value": 11
}

### Postscripts

GET {{baseUrl}}/Postscripts
