@hostname = 127.0.0.1:5000
@endpoint = /v1
@baseUrl = http://{{hostname}}{{endpoint}}
@contentType = application/json

### Students

GET {{baseUrl}}/students

### 

GET {{baseUrl}}/students/65571745183367eeb5aded5b

###

POST {{baseUrl}}/students/
Content-Type: application/json

{
  "firstName": "Foo",
  "lastName": "Bar",
  "scores": [
    {
      "examId": "abc",
      "pointsScored": 5,
      "isPostscript": false
    }
  ]
}

###

PUT {{baseUrl}}/students/6557487f18c545c1f64ff19a
Content-Type: application/json

{
  "id": "6557487f18c545c1f64ff19a",
  "firstName": "NotFoo",
  "lastName": "NotBar",
  "scores": [
    {
      "examId": "abc",
      "pointsScored": 5,
      "isPostscript": false
    }
  ]
}

###

DELETE {{baseUrl}}/students/654e1e1443203b9d84cc87a0
